django/econsensus/econsensus/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.core.urlresolvers import reverse_lazy
from organizations.backends import invitation_backend
from custom_auth.forms import CustomAuthenticationForm, CustomPasswordResetForm
from registration.backends.default.views import RegistrationView
from custom_organizations.forms import CustomUserSignupRegistrationForm

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/logout/$', 'django.contrib.auth.views.logout_then_login',
        {'login_url': reverse_lazy('admin:index')}),
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^settings/', include('livesettings.urls')),
    url(r'^notification/', include('notification.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^organizations/', include('custom_organizations.urls')),
    url(r'^invitations/', include(invitation_backend().get_urls())),
    # the pages adds a / at the start, so don't put the / after pages
    url(r'^pages', include('django.contrib.flatpages.urls')),
    url(r'', include('publicweb.urls')),
)

urlpatterns += patterns(
    '',
    url(r'^accounts/register/$', RegistrationView.as_view(
        form_class=CustomUserSignupRegistrationForm,
        template_name='organizations/register_form.html'),
        name='registration_register'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login'),
    url(r'^accounts/login/$', 'remember_me.views.remember_me_login',
        {'authentication_form': CustomAuthenticationForm},
        name="remember_me_login"),
    url(r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset',
        {'password_reset_form': CustomPasswordResetForm}),
    url(r'^accounts/', include('registration.backends.default.urls')),

)

urlpatterns += staticfiles_urlpatterns()

django/econsensus/publicweb/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView

from views import (DecisionCreate, DecisionUpdate, DecisionDetail, DecisionList,
                    ExportCSV, FeedbackCreate, FeedbackSnippetCreate,
                    FeedbackUpdate, EconsensusActionitemCreateView,
                    EconsensusActionitemUpdateView,
                    EconsensusActionitemListView, OrganizationRedirectView,
                    YourDetails, UserNotificationSettings,
                    EconsensusActionitemDetailView, DecisionSearchView)

from models import Feedback
from publicweb.views import AddWatcher, RemoveWatcher


urlpatterns = patterns('econsensus.publicweb.views',
    url(r'^user_settings/your_details/$',
        YourDetails.as_view(),
        name='your_details'),
    url(r'^user_settings/notification_settings/(?P<org_slug>[-\w]+)/$',
        UserNotificationSettings.as_view(), name='notification_settings'),
    url(r'^add_watcher/(?P<decision_id>\d+)/$', AddWatcher.as_view(),
        name="add_watcher"),
    url(r'^remove_watcher/(?P<decision_id>\d+)/$', RemoveWatcher.as_view(),
        name="remove_watcher"),

    url(r'^(?P<org_slug>[-\w]+)/export_csv/$',
        ExportCSV.as_view(),
        name='publicweb_export_csv'),

    # Feedback urls...
    url(r'^feedback/create/(?P<parent_pk>[\d]+)/$',
        FeedbackCreate.as_view(template_name='feedback_update_page.html'),
        name='publicweb_feedback_create'),
    url(r'^feedback/update/(?P<pk>[\d]+)/$',
        FeedbackUpdate.as_view(template_name='feedback_update_page.html'),
        name='publicweb_feedback_update'),
    url(r'^feedback/detail/(?P<pk>[\d]+)/$',
        login_required(DetailView.as_view(
            model=Feedback,
            template_name='feedback_detail_page.html')),
        name='publicweb_feedback_detail'),
    url(r'^feedback/comment/(?P<pk>[\d]+)/$',
        login_required(DetailView.as_view(
            model=Feedback,
            template_name='feedback_comment_page.html')),
        name='publicweb_feedback_comment'),
    # snippets
    url(r'^feedback/create/snippet/(?P<parent_pk>[\d]+)/$',
        FeedbackSnippetCreate.as_view(
        template_name='feedback_update_snippet.html'),
        name='publicweb_feedback_snippet_create'),
    url(r'^feedback/update/snippet/(?P<pk>[\d]+)/$',
        FeedbackUpdate.as_view(template_name='feedback_update_snippet.html'),
        name='publicweb_feedback_snippet_update'),
    url(r'^feedback/detail/snippet/(?P<pk>[\d]+)/$',
        login_required(DetailView.as_view(
            model=Feedback,
            template_name='feedback_detail_snippet.html')),
        name='publicweb_feedback_snippet_detail'),

    # decision urls...
    url(r'^(?P<org_slug>[-\w]+)/decision/create/(?P<status>[a-z]+)/$',
        DecisionCreate.as_view(template_name='decision_update_page.html'),
        name='publicweb_decision_create'),
    url(r'^decision/update/(?P<pk>[\d]+)/$',
        DecisionUpdate.as_view(template_name='decision_update_page.html'),
        name='publicweb_decision_update'),
    url(r'^decision/detail/(?P<pk>[\d]+)/$',
        DecisionDetail.as_view(template_name='decision_detail_page.html'),
        name='publicweb_decision_detail'),
    # snippets
    url(r'^(?P<org_slug>[-\w]+)/decision/create/snippet/(?P<status>[a-z]+)/$',
        DecisionCreate.as_view(template_name='decision_update_snippet.html'),
        name='publicweb_decision_snippet_create'),
    url(r'^decision/update/snippet/(?P<pk>[\d]+)/$',
        DecisionUpdate.as_view(template_name='decision_update_snippet.html'),
        name='publicweb_decision_snippet_update'),
    url(r'^decision/detail/snippet/(?P<pk>[\d]+)/$',
        DecisionDetail.as_view(template_name='decision_detail_snippet.html'),
        name='publicweb_decision_snippet_detail'),

    # item urls
    url(r'^item/detail/(?P<pk>[\d]+)/$',
        DecisionDetail.as_view(template_name='item_detail.html'),
        name='publicweb_item_detail'),
    url(r'^(?P<org_slug>[-\w]+)/item/list/(?P<status>[a-z]+)/$',
        DecisionList.as_view(template_name='decision_list.html'),
        name='publicweb_item_list'),
    url(r'^(?P<org_slug>[-\w]+)/search/$',
        DecisionSearchView.make(),
        name='publicweb_decision_search'),

    # actionitem urls
    url(r'^item/detail/(?P<pk>[\d]+)/actionitem/add/$',
        EconsensusActionitemCreateView.as_view(),
        name='actionitem_create'),
    url(r'^item/detail/(?P<decisionpk>[\d]+)/actionitem/(?P<pk>[\d]+)/$',
        EconsensusActionitemDetailView.as_view(),
        name='actionitem_detail'),
    url(r'^item/detail/(?P<decisionpk>[\d]+)/actionitem/(?P<pk>[\d]+)/update/$',
        EconsensusActionitemUpdateView.as_view(),
        name='actionitem_update'),
    url(r'^(?P<org_slug>[-\w]+)/actionitem/list/$',
        EconsensusActionitemListView.as_view(),
        name='actionitem_list'),

    url(r'^(?P<org_slug>[-\w]+)/item/list/$',
        DecisionList.as_view(template_name='decision_list.html'),
        name='publicweb_default_item_list'),
    url(r'^$',
        OrganizationRedirectView.as_view(),
        name='publicweb_root'),
    )

django/econsensus/custom_organizations/forms.py
from django import forms

from organizations.models import Organization, get_user_model
from organizations.utils import create_organization
from organizations.backends.forms import UserRegistrationForm
from organizations.forms import OrganizationUserForm, OrganizationUserAddForm
from guardian.shortcuts import assign_perm, remove_perm
from registration.forms import RegistrationFormUniqueEmail
from registration.signals import user_registered
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _


# Subclass the default Registration form so we can add extra fields 
# to the sign up process (first_name and last_name)
# These fields are caught by the user_registered signal
# and saved into the User model
class CustomUserSignupRegistrationForm(RegistrationFormUniqueEmail):
    """Form class for completing a user's registration and activating the
    User."""
    first_name = forms.CharField(max_length=30, label = _("First name"))
    last_name = forms.CharField(max_length=30, label = _("Last name"))

    def __init__(self, *args, **kwargs):
        super(CustomUserSignupRegistrationForm, self).__init__(*args, **kwargs)
        self.initial['username'] = ''
        self.fields.keyOrder = ['username', 'first_name', 'last_name',
                                'email', 'password1', 'password2']

@receiver(user_registered)
def user_created(sender, user, request, **kwargs):
    form = CustomUserSignupRegistrationForm(request.POST)
    user.first_name = form.data['first_name']
    user.last_name = form.data['last_name']
    user.save()


# Subclass the UserRegistrationForm so we can change the labels
class CustomUserRegistrationForm(UserRegistrationForm):
    """Form class for completing a user's registration and activating the
    User."""
    email = forms.CharField(label = _("E-mail"))
    password = forms.CharField(max_length=30, widget=forms.PasswordInput, 
                label = _("Password"))
    password_confirm = forms.CharField(max_length=30,
            widget=forms.PasswordInput, label = _("Password (again)"))

# Completely override OrganizationForm and OrganizationAddForm from 
# organizations.forms because we don't want to allow ownership changes via UI, 
# and we want the owner of new Organizations to be the creating user.
class CustomOrganizationForm(forms.ModelForm):
    """
    For editing Organizations.
    """

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(CustomOrganizationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Organization
        exclude = ('slug', 'users', 'is_active')

class CustomOrganizationAddForm(CustomOrganizationForm):
    """
    For creating new Organizations.
    Set the owner to be the request user. The slug, will be auto-generated 
    from the name.
    """

    def save(self, **kwargs):
        is_active = True
        user = self.request.user
        organization = create_organization(user,
                                           self.cleaned_data['name'],
                                           '',  # Empty slug to be autofilled
                                           is_active=is_active)
        assign_perm('edit_decisions_feedback',
               organization.owner.organization_user.user,
               organization)
        return organization

class CustomOrganizationUserForm(OrganizationUserForm):
    USER_TYPES = (
        ('admin', _("Admin (can edit and invite users)")),
        ('editor', _("Normal User")),
        ('viewer', _("Viewer Only (can't add or edit information)")),
    )
    user_type = forms.ChoiceField(required=True, choices=USER_TYPES) 

    def save(self, commit=True):
        self.instance.is_admin = (self.cleaned_data['user_type'] == 'admin')
        if self.cleaned_data['user_type'] != 'viewer':
            assign_perm('edit_decisions_feedback', self.instance.user, self.instance.organization)
        else:
            remove_perm('edit_decisions_feedback', self.instance.user, self.instance.organization)
        return super(CustomOrganizationUserForm, self).save(commit=commit)

class CustomOrganizationUserAddForm(OrganizationUserAddForm):
    USER_TYPES = (
        ('admin', _("Admin (can edit and invite users)")),
        ('editor', _("Normal User")),
        ('viewer', _("Viewer Only (can't add or edit information)")),
    )
    user_type = forms.ChoiceField(required=True, choices=USER_TYPES)

    def save(self, commit=True):
        self.cleaned_data['is_admin'] = (self.cleaned_data['user_type'] == 'admin')
        self.instance = super(CustomOrganizationUserAddForm, self).save(commit=commit)
        if self.cleaned_data['user_type'] != 'viewer':
            assign_perm('edit_decisions_feedback', self.instance.user, self.instance.organization)
        else:
            remove_perm('edit_decisions_feedback', self.instance.user, self.instance.organization)
        return self.instance

django/econsensus/publicweb/forms.py
# Create your forms here.

from django import forms
from models import Decision, Feedback
from django.contrib.auth.models import User


from django.utils.translation import ugettext_lazy as _
from django.forms.fields import ChoiceField
from django.forms.widgets import RadioSelect

from widgets import JQueryUIDateWidget

from publicweb.models import NotificationSettings, change_observers, \
    additional_message_required, send_decision_notifications

from parsley.decorators import parsleyfy
from actionitems.forms import ActionItemCreateForm, ActionItemUpdateForm
from publicweb.extra_models import MAIN_ITEMS_NOTIFICATIONS_ONLY
from actionitems.models import ActionItem


class YourDetailsForm(forms.ModelForm):

    class Meta:
        model = User
        exclude = ('is_staff', 'is_superuser', 'is_active', 'last_login',
                'date_joined', 'groups', 'user_permissions', 'password')

    def clean_email(self):
        if self.instance.email == self.cleaned_data['email']:
            return self.cleaned_data['email']
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError(
                _(
                    "This email address is already in use. Please supply a "
                    "different email address."
                )
            )
        return self.cleaned_data['email']


class NotificationsForm(forms.ModelForm):
    watch = forms.BooleanField(
        required=False,
        label=_("Watch this conversation"),
        help_text=_(
            "If you check this box, you will receive notifications about "
            "further updates to this conversation. This overrides your "
            "notification settings."
        ),
        initial=True
    )

    def get_decision(self):
        raise NotImplementedError

    def change_observers(self, decision, watcher):
        watch = self.cleaned_data.get('watch', False)
        change_observers(watch, decision, watcher)

    def save(self, commit=True):
        # The only time a decision won't have an id is when it's created.
        # In this case, we'll want to handle it in the post save handler
        decision = self.get_decision()
        if commit and decision.id:
            user = self.instance.editor or self.instance.author
            self.change_observers(decision, user)
        return super(NotificationsForm, self).save(commit)


class FeedbackForm(NotificationsForm):
    minor_edit = forms.BooleanField(required=False, initial=False)

    def get_decision(self):
        return self.instance.decision

    class Meta:
        model = Feedback
        exclude = ("decision",)


@parsleyfy
class DecisionForm(NotificationsForm):

    watch = forms.BooleanField(required=False, initial=True)
    minor_edit = forms.BooleanField(required=False, initial=False)

    def get_decision(self):
        return self.instance

    def save(self, commit=True):
        created = not self.instance.id
        decision = super(DecisionForm, self).save(commit)

        send_new_message = additional_message_required(
           decision.author or decision.editor,
           decision, MAIN_ITEMS_NOTIFICATIONS_ONLY)
        if commit and created:
            self.change_observers(decision, decision.author)
            if send_new_message:
                send_decision_notifications(decision, [decision.author])
        return decision

    class Meta:
        model = Decision
        exclude = ('organization',)
        widgets = {
           'decided_date': JQueryUIDateWidget,
           'effective_date': JQueryUIDateWidget,
           'review_date': JQueryUIDateWidget,
           'expiry_date': JQueryUIDateWidget,
           'archived_date': JQueryUIDateWidget,
           'deadline': JQueryUIDateWidget
        }


EXTRA_CHOICE = (3, _('All'))  # pylint: disable=E1102


@parsleyfy
class EconsensusActionItemCreateForm(ActionItemCreateForm):
    pass
# TODO: Sort and filter forms have nothing to do with the app itself.
# Move to site when site and app are split.


@parsleyfy
class EconsensusActionItemUpdateForm(ActionItemUpdateForm):
    pass


class FilterForm(forms.Form):
    # this seems clunky...
    list_choices = list(Decision.STATUS_CHOICES)
    list_choices.append(EXTRA_CHOICE)
    FILTER_CHOICES = tuple(list_choices)
    filtar = ChoiceField(choices=FILTER_CHOICES,
                         label=_('Status'),  # pylint: disable=E1102
                         initial=EXTRA_CHOICE[0],
                         required=False,
                         widget=forms.Select(
                             attrs={'onchange': 'this.form.submit()'}
                         ))


class NotificationSettingsForm(forms.ModelForm):

    class Meta:
        model = NotificationSettings
        exclude = ('user', 'organization')
        widgets = {
            'notification_level': RadioSelect
        }

django/econsensus/publicweb/templates/organizations/organization_admin.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}
{% load org_tags %}
{% load org_filters %}

{% block title %}
{{ organization }} admin page
{% endblock %}

{% block heading %}
{{ organization }} admin page
{% endblock %}

{% block main_content %}
<div id="organization-admin">
<ul>
    {% if organization|is_admin:user %}
    <li>
        <a href="{% url 'organization_edit' organization.pk %}">{% trans "Rename Organization" %}</a>
    </li>
    <li>
        <a href="{% url 'organization_user_list' organization.pk %}">{% trans "Manage Members" %}</a>
    </li>
    {% endif %}
    {% if organization|is_owner:user %}
    <li>
        <a href="{% url 'organization_delete' organization.pk %}">{% trans "Delete Organization" %}</a>
    </li>
    {% endif %}
</ul>

<ul>
<br />
<br />
    <li><a href="{% url 'organization_list' %}">Back to your organizations</a> </li>
</ul>

</div>
{% endblock %}

django/econsensus/publicweb/templates/organizations/organization_confirm_delete.html
{% extends "base_org_admin.html" %}
{% load i18n %}
{% load url from future %}


{% block title %}
Confirm Delete
{% endblock %}

{% block heading %}
Confirm Delete
{% endblock %}

{% block main_content %}
<h1>{{ account }}</h1>
<h3>Are you sure you want to delete this organization?</h3>
<br />
<form action="." method="post">{% csrf_token %}
    {{ form }}
    <input class = "loose button" type="submit" value="Delete">
</form>
<form method="GET" action="{% url 'organization_list' %}">
    <input class="loose button" type="submit" value="Cancel">
</form>
{% endblock %}

django/econsensus/publicweb/templates/organizations/organization_detail.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}
{% load org_tags %}
{% load org_filters %}
{% block title %}
{{ organization }}
{% endblock %}

{% block header %}{{ organization }}{% endblock %}

{% block heading %}
{{ organization }}
{% endblock %}

{% block main_content %}
<ul>
{% for organization_user in organization_users %}
{% if organization_user.user.is_active %}
<li>{{ organization_user.user }}</li>
{% endif %}
{% endfor %}
</ul>

{% organization_users organization %}
<ul>
<br />
    <li><a href="{% url 'organization_user_add' organization.pk %}">Add a new member</a></li>
{% endblock %}
</ul>

django/econsensus/publicweb/templates/organizations/organization_form.html
{% extends "base_org_admin.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}
{% if organization %}{{ organization.name }}{% else %}{% trans 'Create New Organization' %}{% endif %}
{% endblock %}

{% block heading %}{% if organization %}{{ organization.name }}{% else %}{% trans 'Create New Organization' %}{% endif %}{% endblock %}

{% block main_content %}
{% include 'organizations/organization_form_snippet.html' %}
{% endblock %}

django/econsensus/publicweb/templates/organizations/organization_form_snippet.html
{% load i18n %}
{% load url from future %}
<!-- a quick and dirty fix, hmm -->
<br />
<br />
{% if organization %}
<p>{% trans 'Enter the new name for your organization and then click "OK"' %}</p>
{% else %}
<p>{% trans "If you create an organization, you will be the owner of that organization. This means that: "%}</p>
<br />
<ul class="bulleted">
    <li> {% trans "you will always be an admin for your organization. This gives you the ability to invite and remove people from your organization, and change their permissions." %} </li>
<br />
    <li> {% trans "you have the right to delete the organization." %}</li>
</ul>
<br />

<p>{% trans "This is all available in the organization admin interface, which will become available once you have created the organization." %}</p>
<br />
<p>{% trans 'Enter the name of your organization and then click "OK"' %}</p>
{% endif %}
<br />
<form method="post">{% csrf_token %}
    {% for field in form %}
        {{ field.errors }}
        {{ field }}
    {% endfor %}
    <br />
    <br />
    <input class="loose button" type="submit" value="OK">
</form>

<form method="GET" action="{% url 'organization_list' %}">
    <input class="loose button" type="submit" value="Cancel">
</form>
<br />

django/econsensus/publicweb/templates/organizations/organization_list.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}
{% load org_tags %}
{% load org_filters %}

{% block title %}
{% trans "Your Organizations" %}
{% endblock %}

{% block heading %}
{% trans "Your Organizations" %}
{% endblock %}

{% block main_content %}
<div id="your-organizations">
{% for organization in organizations %}
{% if forloop.first %}<ul class="org_list">{% endif %}
    <li>
        <ul>
        <li>
            <a href="{% url 'publicweb_item_list' organization.slug 'discussion'%}">{{ organization.name }}</a>
        </li>
            <li>
                {% if organization|is_owner:user %}
                <span>{% trans "owner" %}</span>
                {% else %}
                <a href="{% url 'organization_user_leave' organization.pk %}">{% trans "leave" %}</a>
                {% endif %}
            </li>
            {% if organization|is_admin:user %}
            <li>
                <a href="{% url 'organization_admin' organization.pk %}">{% trans "admin" %}</a>
            </li>
            {% endif %}
            <li>
                <a href="{% url 'notification_settings' organization.slug %}">{% trans "notification settings" %}</a>
            </li>
        </ul>
    </li>
{% if forloop.last %}</ul>{% endif %}
{% empty %}
<p>{% trans "You do not currently belong to any organizations."%}</p>
<p>{% trans "You can only view and create discussions, proposals and decisions when you belong to an organization so try one of the following ..."%}</p>
<ul class="bulleted">
    <li>{% trans "create a new organization - use the link below - you can then invite other users to join you and start the econsensus process" %}</li>
    <li>{% trans "or, contact an administrator of an existing organization and request to be added as a member - you'll need to supply the email address you registered this user with" %}</li>
</ul>
{% endfor %}
<div>
<a title="{% trans 'Create New Organization' %}" href="{% url 'organization_add' %}">{% trans "Create New Organization" %}</a>
</div>
</div>

{% endblock %}

django/econsensus/publicweb/templates/organizations/organization_users.html
{% load url from future %}

<ul>
    {% for organization_user in organization_users %}
    <li>
    <a href="{{ organization_user.get_absolute_url }}">{{ organization_user }}</a>
    {% if not organization_user.user.is_active %}<a href="{% url 'organization_user_remind' organization.id organization_user.user.id %}">Send reminder</a>{% endif %}
    </li>
    {% endfor %}
</ul>

django/econsensus/publicweb/templates/organizations/organizationuser_confirm_delete.html
{% extends "base_org_admin.html" %}
{% load url from future %}
{% load i18n %}
{% load org_tags %}

{% block title %}
Confirm remove
{% endblock %}

{% block heading %}
{% if organization_user.user.is_active %}
Confirm removal of {{ organization_user.user }} from {{ organization }}.
{% else %}
Confirm removal of {{ organization_user.user.email }} from {{ organization }}.
{% endif %}
{% endblock %}

{% block main_content %}
<br />
<br />
Removing a user will only remove the user from your organization, {{ organization }}.
<br />
<br />
The user will not be removed from econsensus
<br />
<br />
<form action="." method="post">{% csrf_token %}
    {{ form }}
    <input class="loose button" type="submit" value="Remove">
</form>

<form method="GET" action="{% url 'organization_user_list' organization.pk%}">
    <input class="loose button" type="submit" value="Cancel">
</form>
<br />
{% endblock %}

django/econsensus/publicweb/templates/organizations/organizationuser_confirm_leave.html
{% extends "base_org_admin.html" %}
{% load url from future %}
{% load i18n %}
{% load org_tags %}

{% block title %}
Confirm leaving {{ organization }}
{% endblock %}

{% block heading %}
Confirm that you want to leave {{ organization }}
{% endblock %}

{% block main_content %}
<br />
<br />
Once you have left {{ organization }} you cannot rejoin by yourself - you will have
to be re-invited by an admin.
<br />
<br />
<form action="." method="post">{% csrf_token %}
    {{ form }}
    <input class="loose button" type="submit" value="Leave">
</form>

<form method="GET" action="{% url 'organization_list' %}">
    <input class="loose button" type="submit" value="Cancel">
</form>
<br />
{% endblock %}

django/econsensus/publicweb/templates/organizations/organizationuser_form.html
{% extends "base_org_admin.html" %}
{% load url from future %}

{% load i18n %}
{% load org_tags %}


{% block title %}
User form
{% endblock %}

{% block heading %}
{% if organization_user.user %}
Details for {{ organization_user.user }}
{% else %}
Add new member 
{% endif %}
{% endblock %}

{% block main_content %}
{% if user == organization_user.user %}This is you!{% endif %}

<br />
<br />
{% if not organization_user.user %}
<p>
Users who do not have an econsensus account will be emailed an invite <br /> to sign up before they join your organisation. 
<br />
<br />
If they already have an account they will be able to use your <br />organization immediately.
</p>
{% else %}
<p>
Change user permissions below 
</p>
{% endif %}
<br />

<form action="." method="post">{% csrf_token %}
    {{ form.non_field_errors }}
	{% if form.email %}
    <div class="fieldWrapper">
    	{{ form.email.errors }}
    	<label for="id_email">Enter email: </label>
    	{{ form.email }}
    </div>
    {% endif %}
    <div class="fieldWrapper">
        <label for = "id_email">User Type:</label>
        {{ form.user_type }}
    </div>    
<br />
    <input class="loose button" type="submit" value="OK">
</form>
<form method="GET" action="{% url 'organization_user_list' organization.pk %}">
    <input class="loose button" type="submit" value="Cancel">
</form>
<br />

{% endblock %}

django/econsensus/publicweb/templates/organizations/organizationuser_remind.html
{% extends "base_org_admin.html" %}
{% load i18n %}
{% load url from future %}


{% block title %}
Send reminder
{% endblock %}

{% block heading %}
Send reminder to {{ organization_user.user.email }}

{% endblock %}

{% block main_content %}
<br />
<br />
<form action="." method="post">{% csrf_token %}
    {{ form }}
    <input class="loose button" type="submit" value="Send reminder">
</form>
<form method="GET" action="{% url 'organization_user_list' organization.pk%}">
    <input class="loose button" type="submit" value="Cancel">
</form>
<br />

{% endblock %}

django/econsensus/publicweb/templates/organizations/register_form.html
{% extends "base.html" %}
{% load i18n %}

{% block body_class%}
login
{% endblock %}

{% block title %}
Registration
{% endblock %}

{% block user_access %}
{% endblock %}

{% block topbar%}
{% endblock %}

{% block head %}
{{ form.media }}
{% endblock %}

{% block heading %}
Registration
{% endblock %}

{% block main_content %}
<form id="short-form" method="post" action=".">
  {% csrf_token %}
  {% for field in form %}
  <div class="field">
    <p class="label">{{ field.label_tag }}</p>
    <p class="field_value">{{ field }}</p>
    <p class="errorlist">{{ field.errors.as_text }}</p>
  </div>
  {% endfor %}
  
<div class="button_group">
  <input class="button" type="submit" value="{% trans 'Submit' %}" />
</div>
</form>
{% endblock %}

django/econsensus/publicweb/templates/organizations/register_success.html
{% extends "base.html" %}
{% load i18n %}
{% load org_tags %}

{% block title %}
Registration Success
{% endblock %}

{% block heading %}
Registration Success
{% endblock %}

{% block main_content %}
Thanks!
{% endblock %}