django/econsensus/econsensus/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.core.urlresolvers import reverse_lazy
from organizations.backends import invitation_backend
from custom_auth.forms import CustomAuthenticationForm, CustomPasswordResetForm
from registration.backends.default.views import RegistrationView
from custom_organizations.forms import CustomUserSignupRegistrationForm

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/logout/$', 'django.contrib.auth.views.logout_then_login',
        {'login_url': reverse_lazy('admin:index')}),
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^settings/', include('livesettings.urls')),
    url(r'^notification/', include('notification.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^organizations/', include('custom_organizations.urls')),
    url(r'^invitations/', include(invitation_backend().get_urls())),
    # the pages adds a / at the start, so don't put the / after pages
    url(r'^pages', include('django.contrib.flatpages.urls')),
    url(r'', include('publicweb.urls')),
)

urlpatterns += patterns(
    '',
    url(r'^accounts/register/$', RegistrationView.as_view(
        form_class=CustomUserSignupRegistrationForm,
        template_name='organizations/register_form.html'),
        name='registration_register'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login'),
    url(r'^accounts/login/$', 'remember_me.views.remember_me_login',
        {'authentication_form': CustomAuthenticationForm},
        name="remember_me_login"),
    url(r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset',
        {'password_reset_form': CustomPasswordResetForm}),
    url(r'^accounts/', include('registration.backends.default.urls')),

)

urlpatterns += staticfiles_urlpatterns()

django/econsensus/publicweb/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView

from views import (DecisionCreate, DecisionUpdate, DecisionDetail, DecisionList,
                    ExportCSV, FeedbackCreate, FeedbackSnippetCreate,
                    FeedbackUpdate, EconsensusActionitemCreateView,
                    EconsensusActionitemUpdateView,
                    EconsensusActionitemListView, OrganizationRedirectView,
                    YourDetails, UserNotificationSettings,
                    EconsensusActionitemDetailView, DecisionSearchView)

from models import Feedback
from publicweb.views import AddWatcher, RemoveWatcher


urlpatterns = patterns('econsensus.publicweb.views',
    url(r'^user_settings/your_details/$',
        YourDetails.as_view(),
        name='your_details'),
    url(r'^user_settings/notification_settings/(?P<org_slug>[-\w]+)/$',
        UserNotificationSettings.as_view(), name='notification_settings'),
    url(r'^add_watcher/(?P<decision_id>\d+)/$', AddWatcher.as_view(),
        name="add_watcher"),
    url(r'^remove_watcher/(?P<decision_id>\d+)/$', RemoveWatcher.as_view(),
        name="remove_watcher"),

    url(r'^(?P<org_slug>[-\w]+)/export_csv/$',
        ExportCSV.as_view(),
        name='publicweb_export_csv'),

    # Feedback urls...
    url(r'^feedback/create/(?P<parent_pk>[\d]+)/$',
        FeedbackCreate.as_view(template_name='feedback_update_page.html'),
        name='publicweb_feedback_create'),
    url(r'^feedback/update/(?P<pk>[\d]+)/$',
        FeedbackUpdate.as_view(template_name='feedback_update_page.html'),
        name='publicweb_feedback_update'),
    url(r'^feedback/detail/(?P<pk>[\d]+)/$',
        login_required(DetailView.as_view(
            model=Feedback,
            template_name='feedback_detail_page.html')),
        name='publicweb_feedback_detail'),
    url(r'^feedback/comment/(?P<pk>[\d]+)/$',
        login_required(DetailView.as_view(
            model=Feedback,
            template_name='feedback_comment_page.html')),
        name='publicweb_feedback_comment'),
    # snippets
    url(r'^feedback/create/snippet/(?P<parent_pk>[\d]+)/$',
        FeedbackSnippetCreate.as_view(
        template_name='feedback_update_snippet.html'),
        name='publicweb_feedback_snippet_create'),
    url(r'^feedback/update/snippet/(?P<pk>[\d]+)/$',
        FeedbackUpdate.as_view(template_name='feedback_update_snippet.html'),
        name='publicweb_feedback_snippet_update'),
    url(r'^feedback/detail/snippet/(?P<pk>[\d]+)/$',
        login_required(DetailView.as_view(
            model=Feedback,
            template_name='feedback_detail_snippet.html')),
        name='publicweb_feedback_snippet_detail'),

    # decision urls...
    url(r'^(?P<org_slug>[-\w]+)/decision/create/(?P<status>[a-z]+)/$',
        DecisionCreate.as_view(template_name='decision_update_page.html'),
        name='publicweb_decision_create'),
    url(r'^decision/update/(?P<pk>[\d]+)/$',
        DecisionUpdate.as_view(template_name='decision_update_page.html'),
        name='publicweb_decision_update'),
    url(r'^decision/detail/(?P<pk>[\d]+)/$',
        DecisionDetail.as_view(template_name='decision_detail_page.html'),
        name='publicweb_decision_detail'),
    # snippets
    url(r'^(?P<org_slug>[-\w]+)/decision/create/snippet/(?P<status>[a-z]+)/$',
        DecisionCreate.as_view(template_name='decision_update_snippet.html'),
        name='publicweb_decision_snippet_create'),
    url(r'^decision/update/snippet/(?P<pk>[\d]+)/$',
        DecisionUpdate.as_view(template_name='decision_update_snippet.html'),
        name='publicweb_decision_snippet_update'),
    url(r'^decision/detail/snippet/(?P<pk>[\d]+)/$',
        DecisionDetail.as_view(template_name='decision_detail_snippet.html'),
        name='publicweb_decision_snippet_detail'),

    # item urls
    url(r'^item/detail/(?P<pk>[\d]+)/$',
        DecisionDetail.as_view(template_name='item_detail.html'),
        name='publicweb_item_detail'),
    url(r'^(?P<org_slug>[-\w]+)/item/list/(?P<status>[a-z]+)/$',
        DecisionList.as_view(template_name='decision_list.html'),
        name='publicweb_item_list'),
    url(r'^(?P<org_slug>[-\w]+)/search/$',
        DecisionSearchView.make(),
        name='publicweb_decision_search'),

    # actionitem urls
    url(r'^item/detail/(?P<pk>[\d]+)/actionitem/add/$',
        EconsensusActionitemCreateView.as_view(),
        name='actionitem_create'),
    url(r'^item/detail/(?P<decisionpk>[\d]+)/actionitem/(?P<pk>[\d]+)/$',
        EconsensusActionitemDetailView.as_view(),
        name='actionitem_detail'),
    url(r'^item/detail/(?P<decisionpk>[\d]+)/actionitem/(?P<pk>[\d]+)/update/$',
        EconsensusActionitemUpdateView.as_view(),
        name='actionitem_update'),
    url(r'^(?P<org_slug>[-\w]+)/actionitem/list/$',
        EconsensusActionitemListView.as_view(),
        name='actionitem_list'),

    url(r'^(?P<org_slug>[-\w]+)/item/list/$',
        DecisionList.as_view(template_name='decision_list.html'),
        name='publicweb_default_item_list'),
    url(r'^$',
        OrganizationRedirectView.as_view(),
        name='publicweb_root'),
    )

django/econsensus/publicweb/models.py
# pylint: disable=E1102
# config import is unused but required here for livesettings
import config  # pylint: disable=W0611
import re

from notification import models as notification

from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _, ugettext_noop
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.conf import settings
from django.contrib.sites.models import Site
from django.db.models import Count

from tagging.fields import TagField
from organizations.models import Organization
from managers import DecisionManager

from publicweb.utils import get_excerpt

# Ideally django-tinymce should be patched
# http://south.aeracode.org/wiki/MyFieldsDontWork
# http://code.google.com/p/django-tinymce/issues/detail?id=80
# TODO: Status codes could possibly be harvested off into its
# own class with accessor methods to return values.

from south.modelsinspector import add_introspection_rules
from signals.management import (DECISION_CHANGE, MINOR_CHANGE, DECISION_NEW,
    FEEDBACK_NEW, FEEDBACK_CHANGE, COMMENT_NEW, DECISION_STATUS_CHANGE)
from publicweb.observation_manager import ObservationManager
# The NotificationSettings and OrganizationSettings models were moved to a
# separate file to prevent circular imports. They need to be here or django
# won't detect them.
from publicweb.extra_models import (STANDARD_SENDING_HEADERS,
    NotificationSettings, MINOR_CHANGES_NOTIFICATIONS)  # pylint: disable=W0611
from django.dispatch.dispatcher import receiver
from django.contrib.comments.models import Comment
from django.contrib.comments.signals import comment_was_posted

add_introspection_rules([], ["^tagging\.fields\.TagField"])


class Decision(models.Model):

    TAGS_HELP_FIELD_TEXT = "Enter a list of tags separated by spaces."
    DISCUSSION_STATUS = 'discussion'
    PROPOSAL_STATUS = 'proposal'
    DECISION_STATUS = 'decision'
    ARCHIVED_STATUS = 'archived'

    STATUS_CHOICES = (
                  (DISCUSSION_STATUS, _('discussion')),
                  (PROPOSAL_STATUS, _('proposal')),
                  (DECISION_STATUS, _('decision')),
                  (ARCHIVED_STATUS, _('archived')),
                  )

    DEFAULT_SIZE = 140

    # User entered fields
    description = models.TextField(verbose_name=_('Description'))
    decided_date = models.DateField(null=True, blank=True,
        verbose_name=_('Decided Date'))
    effective_date = models.DateField(null=True, blank=True,
        verbose_name=_('Effective Date'))
    review_date = models.DateField(null=True, blank=True,
        verbose_name=_('Review Date'))
    expiry_date = models.DateField(null=True, blank=True,
        verbose_name=_('Expiry Date'))
    deadline = models.DateField(null=True, blank=True,
        verbose_name=_('Deadline'))
    archived_date = models.DateField(null=True, blank=True,
        verbose_name=_('Archived Date'))
    budget = models.CharField(blank=True, max_length=255,
        verbose_name=_('Budget/Resources'))
    people = models.CharField(max_length=255, null=True, blank=True)
    meeting_people = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(choices=STATUS_CHOICES,
                                 default=PROPOSAL_STATUS,
                                 max_length=10)
    tags = TagField(null=True, blank=True, editable=True,
                    help_text=TAGS_HELP_FIELD_TEXT)
    organization = models.ForeignKey(Organization)
    # admin stuff
    author = models.ForeignKey(User, blank=True, null=True, editable=False, related_name="%(app_label)s_%(class)s_authored")
    editor = models.ForeignKey(User, blank=True, null=True, editable=False, related_name="%(app_label)s_%(class)s_edited")
    last_modified = models.DateTimeField(null=True, auto_now_add=True, verbose_name=_('Last Modified'))
    last_status = models.CharField(choices=STATUS_CHOICES,
                                 default="new",
                                 max_length=10, editable=False)

    watchers = generic.GenericRelation(notification.ObservedItem)

    # Autocompleted fields
    # should use editable=False?
    excerpt = models.CharField(verbose_name=_('Excerpt'), max_length=255, blank=True)
    creation = models.DateField(null=True, auto_now_add=True,
        verbose_name=_('Creation'))

    objects = DecisionManager()

    # Fields that'll trigger last_modified update upon change
    TRIGGER_FIELDS = ('description', 'decided_date', 'effective_date', 'review_date',
              'expiry_date', 'deadline', 'archived_date', 'budget', 'people',
              'meeting_people', 'excerpt', 'creation')

    def __init__(self, *args, **kwargs):
        # Unpersisted flag for suppressing notifications at save time
        self.minor_edit = False

        super(Decision, self).__init__(*args, **kwargs)

    # methods
    def unresolvedfeedback(self):
        answer = _("No")
        linked_feedback = self.feedback_set.all()
        for thisfeedback in linked_feedback:
            if (not thisfeedback.resolved):

                answer = _("Yes")
                break

        return answer

    unresolvedfeedback.short_description = _("Unresolved Feedback")

    def feedbackcount(self):
        return self.feedback_set.all().count()

    feedbackcount.short_description = _("Feedback")

    def _get_excerpt(self):
        return get_excerpt(self.description)

    def __unicode__(self):
        return self.excerpt

    @classmethod
    def get_fields(cls):
        return cls._meta.fields

    @models.permalink
    def get_absolute_url(self):
        return ('publicweb_item_detail', [self.id])

    def get_email(self):
        """
        Generates an email address based on the Decision's organization
        and settings.DEFAULT_FROM_EMAIL
        """
        default_from_email = settings.DEFAULT_FROM_EMAIL
        return re.sub('\w+@', "%s@" % self.organization.slug, default_from_email)

    def get_feedback_statistics(self):
        statistics = dict([(unicode(x), 0) for x in Feedback.rating_names])
        raw_data = self.feedback_set.values('rating').annotate(Count('rating'))
        for x in raw_data:
            key = unicode(Feedback.rating_names[x['rating']])
            statistics[key] = x['rating__count']
        return statistics

    def get_message_id(self):
        """
        Generates a message id that can be used in email headers
        """
        return "<decision-%s@%s>" % (self.id, Site.objects.get_current().domain)

    def _send_change_notifications(self, notification_type):
        headers = {'Message-ID': self.get_message_id()}
        headers.update(STANDARD_SENDING_HEADERS)
        org_users = self.organization.users.all()
        observation_manager = ObservationManager()
        observation_manager.send_notifications(org_users, self, notification_type, {"observed": self}, headers=headers, from_email=self.get_email())

    def _send_minor_change_notifications(self):
        self._send_change_notifications(MINOR_CHANGE)

    def _send_major_change_notifications(self):
        self._send_change_notifications(DECISION_CHANGE)

    def _is_same(self, other):
        for field in self.TRIGGER_FIELDS:
            my_field = getattr(self, field)
            other_field = getattr(other, field)
            if (my_field != other_field
                and not (my_field == u'' and other_field is None)):
                return False
        return True

    def _update_last_modified(self):
        self.last_modified = timezone.now()

    def save(self, *args, **kwargs):
        self.excerpt = self._get_excerpt()
        if self.id:
            prev = self.__class__.objects.get(id=self.id)
            if prev.organization.id != self.organization.id:
                self.watchers.all().delete()

            notification_sent = False
            if self.status != prev.status:
                self._send_change_notifications(DECISION_STATUS_CHANGE)
                self._update_last_modified()
                notification_sent = True

            if not self._is_same(prev) and not notification_sent:
                if not self.minor_edit:
                    self._send_major_change_notifications()
                else:
                    self._send_minor_change_notifications()
                self._update_last_modified()

        super(Decision, self).save(*args, **kwargs)

    def note_external_modification(self):
        """
        Called when some other object is saved (e.g. a comment
        and we want this to be reflected in this decision's
        "last modified" date.
        """
        self._update_last_modified()
        # Go to superclass to avoid sending email notifications
        super(Decision, self).save()


class Feedback(models.Model):

    rating_names = (ugettext_noop('question'),
                    ugettext_noop('danger'),
                    ugettext_noop('concerns'),
                    ugettext_noop('consent'),
                    ugettext_noop('comment'))

    RATING_CHOICES = [(rating_names.index(x), x) for x in rating_names]

    QUESTION_STATUS = rating_names.index('question')
    DANGER_STATUS = rating_names.index('danger')
    CONCERNS_STATUS = rating_names.index('concerns')
    CONSENT_STATUS = rating_names.index('consent')
    COMMENT_STATUS = rating_names.index('comment')

    description = models.TextField(verbose_name=_('Description'), null=True, blank=True)
    author = models.ForeignKey(User, blank=True, null=True, editable=False, related_name="%(app_label)s_%(class)s_related")
    editor = models.ForeignKey(User, blank=True, null=True, editable=False, related_name="%(app_label)s_%(class)s_edited")
    decision = models.ForeignKey('Decision', verbose_name=_('Decision'))
    resolved = models.BooleanField(verbose_name=_('Resolved'))
    rating = models.IntegerField(choices=RATING_CHOICES, default=COMMENT_STATUS)

django/econsensus/publicweb/templates/actionitem_create_snippet.html
{% load i18n %}
{% load url from future %}
{% load waffle_tags %}

{% block main_content %}
{% switch "actionitems" %}
    <form class="actionitem-form" action="{% url 'actionitem_create' pk=form.origin.value %}" method="POST">{% csrf_token %}
        <div class="formset_item actionitem">
            <div class="form_item{{form.description.html_name}}">
                <span{% if form.description.errors %} class="error"{% endif %}>{{ form.description.errors }}{{ form.description }}</span>
            </div>
            <div class="form_item {{form.responsible.html_name}}">
                {{ form.responsible.label_tag }} <span{% if form.responsible.errors %} class="error"{% endif %}>{{ form.responsible.errors }}{{ form.responsible }}</span>
            </div>
            <div class="form_item {{form.deadline.html_name}}">
                {{ form.deadline.label_tag }} <span{% if form.deadline.errors %} class="error"{% endif %}>{{ form.deadline.errors }}{{ form.deadline }}</span>
            </div>
            <div class="form_item {{form.done.html_name}}">
                {{ form.done.label_tag }} <span{% if form.done.errors %} class="error"{% endif %}>{{ form.done.errors }}{{ form.done }}</span>
            </div>
            <div class="controls">
					<input class="button go actionitem_save" type="submit" name="submit" value="{% trans "Save" %}" />
					<input class="button go actionitem_cancel" type="submit" name="submit" value="{% trans "Cancel" %}" />
            </div>
            <input type="hidden" name="origin" value={{form.origin.value}} id="id_origin" />
            <input type="hidden" name="manager" value={{form.manager.value}} id="id_manager" />
        </div>
    </form>
    <script>
        $(function () {
            $('.actionitems-date-widget').datepicker({ dateFormat: "dd/mm/yy"});
        });
    </script>
{% endswitch %}
{% endblock %}

django/econsensus/publicweb/templates/actionitem_detail_snippet.html
{% load url from future %}
{% load i18n %}
{% load guardian_tags %}
{% load waffle_tags %}

{% switch "actionitems" %}
{% get_obj_perms request.user for object.origin.organization as "organization_permissions" %}

<li id="act_id_{{ actionitem.id }}">
       <div class="actionitem_feedback_wrapper {{ data|default:"ActionItem" }}">

	 <div class="actionitem_type {{ data|default:"ActionItem" }}">
	   {{ data|default:"Action Item" }}
	 </div>

	 <div class="description">
	   
	   <span class="actionitem_number">Action Item {{actionitem.id}}:</span>

	   
	   <div class="actionitem_metadata">
	     <ul>
	       <li>{% trans " Responsible: " %}<span class="actionitem_responsible">{{ actionitem.responsible }}</span></li>
	       <li>
		 {% if actionitem.deadline %}{% trans "By " %}<span class="actionitem_responsible">{{ actionitem.deadline }}</span>
		 {% else %}{% trans "No deadline" %}
		 {% endif %}
	       </li>
	     </ul>
	   </div>
	   
	   <p> {% if actionitem.done %}<del>{% endif %} 
	       {{ actionitem.description|urlize|linebreaksbr }} 
	       {% if actionitem.done %}</del>{% endif %} <br />
	   </p>

	   {% if "edit_decisions_feedback" in organization_permissions %}
	   <a class="edit button actionitem" href='{% url 'actionitem_update' decisionpk=actionitem.origin_id pk=actionitem.id %}'>{% trans "Edit" %}</a>
	   {% endif %}
	   
	 </div>
       </div>
</li>
{% endswitch %}

django/econsensus/publicweb/templates/actionitem_update_snippet.html
{% load i18n %}
{% load url from future %}
{% load waffle_tags %}

{% switch "actionitems" %}
{% block main_content %}
    <form class="actionitem-form" action="{% url 'actionitem_update' decisionpk=object.origin_id pk=object.id %}" method="POST">{% csrf_token %}
        <div class="formset_item actionitem">
            <div class="form_item {{form.description.name}}">
                <span{% if form.description.errors %} class="error"{% endif %}>{{ form.description.errors }}{{ form.description }}</span>
            </div>
            <div class="form_item {{form.responsible.html_name}}">
                {{ form.responsible.label_tag }} <span{% if form.responsible.errors %} class="error"{% endif %}>{{ form.responsible.errors }}{{ form.responsible }}</span>
            </div>
            <div class="form_item {{form.deadline.html_name}}">
                {{ form.deadline.label_tag }} <span{% if form.deadline.errors %} class="error"{% endif %}>{{ form.deadline.errors }}{{ form.deadline }}</span>
            </div>
            <div class="form_item {{form.done.html_name}}">
                {{ form.done.label_tag }} <span{% if form.done.errors %} class="error"{% endif %}>{{ form.done.errors }}{{ form.done }}</span>
            </div>
            <div class="controls">
					<input class="button go actionitem_save" type="submit" name="submit" value="{% trans "Save" %}"/>
					<input class="button go actionitem_cancel" type="submit" name="submit" value="{% trans "Cancel" %}" />
            </div>
        </div>
    </form>
    <script>
        $(function () {
        	$('.actionitems-date-widget').datepicker({ dateFormat: "dd/mm/yy"});
        });
    </script>
{% endblock %}
{% endswitch %}

django/econsensus/publicweb/templates/datepicker.html
<input type="{{ type }}" name="{{ name }}"{% if value %} value="{{ value }}"{% endif %}{% if required %} required{% endif %}{% for attr in attrs.items %} {{ attr.0 }}{% if attr.1 %}="{{ attr.1 }}"{% endif %}{% endfor %} />

<script type="text/javascript">
    $(function() {
        var options = {
            dateFormat: 'yy-mm-dd'
        };
        $( "#{{ attrs.id }}" ).datepicker(options);
    });
</script>

django/econsensus/publicweb/templates/decision_detail_page.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{{ object.excerpt}}
{% endblock %}

{% block head_content %}
{{ object.media }}
{% endblock %}

{% block heading %}
<span>
{% if object.status == 'proposal' %}
Proposal
{% else %}
{% if object.status == 'decision' %}
Decision
{% else %}
Archived
{% endif %} {% endif %}
</span>
{% endblock %}

{% block main_content %}
{% include 'decision_detail_snippet.html' %}
{% endblock %}

django/econsensus/publicweb/templates/decision_update_page.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% if form.instance.id %}
	{{ form.instance.excerpt|safe }}
{% else %}
{% trans "Create" %} {{ tab|capfirst }}
{% endif %}{% endblock %}

{% block body_class%}decision-view{% endblock %}

{% block head_content %}
{{ form.media }}
{% endblock %}

{% block heading %}
{% if form.instance.id %}
{% trans "Update"%} {{ tab|capfirst }} #{{ form.instance.id }}
{% else %}
{% trans "Create" %} {{ tab|capfirst }}
{% endif %}
{% endblock %}

{% block main_content %}
{% include 'decision_update_snippet.html' %}
{% endblock %}

django/econsensus/publicweb/templates/feedback_comment_page.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Comment" %}{% endblock %}

{% block heading %}{% trans "Comment" %}{% endblock %}

{% block main_content %}
    {% include "feedback_comment_snippet.html" %}
{% endblock %}

django/econsensus/publicweb/templates/feedback_comment_snippet.html
{% load i18n %}
{% load comments %}

{% with object.get_parent_url as next %}
    {% render_comment_form for object %}
{% endwith %}

django/econsensus/publicweb/templates/feedback_detail_page.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
Feedback Detail
{% endblock %}

{% block heading %}
Feedback
{% endblock %}

{% block main_content %}
<div class="decision_feedback">
	<ol class="feedback_list">
	{% include "feedback_detail_snippet.html" %}
	</ol>
</div>
{% endblock %}

django/econsensus/publicweb/templates/feedback_detail_snippet.html
{% load url from future %}
{% load i18n %}	
{% load comments %}
{% load guardian_tags %}
{% load publicweb_filters %}

{% comment %}Define organization_permissions here to cover case where this template is used to re-render a feedback detail following an inline javascript update of that feedback.{% endcomment %}
{% get_obj_perms request.user for object.decision.organization as "organization_permissions" %}
{% get_comment_list for object as comment_list %}

<li id="id{{ object.id }}">
  <div class="feedback_wrapper {{ object.get_rating_display }}"> 
    <div class="feedback_type {{ object.get_rating_display }}">
      {{ object.get_rating_display|capfirst }}
    </div>
    <div class="description"> 
	  <span class="author">{{ object.get_author_name }} says:</span>
	  <p>{{ object.description|urlize|linebreaksbr }}</p>
	  {% if "edit_decisions_feedback" in organization_permissions %}
	  <a class="button edit" href='{% url 'publicweb_feedback_update' object.id %}'>{% trans "Edit" %}</a>
	  <a class="button show" href='{% url 'publicweb_feedback_comment' object.id %}'>{% trans "Reply" %}</a>
{% endif %}
    </div>
		
	<div class="contrib_comment_container">
	  <ul class="contrib_comment_list">
	  {% for comment in comment_list %}
		<li class = "contrib_comment" id="c{{ comment.object_pk }}_{{ comment.pk }}">
        <span class="author">{{ comment|get_user_name_from_comment }} says:</span>
		  <p>{{ comment.comment|urlize|linebreaksbr }}</p>
		</li>
		  {% endfor %}
	  </ul>

        <div class="showable">
	    {% include "feedback_comment_snippet.html" %}
        </div>
    </div>
  </div>
</li>

django/econsensus/publicweb/templates/feedback_rating_count_snippet.html
{% load i18n %}
{% load publicweb_filters %}

<dt class="{{rating}}">{% trans rating %}</dt>
<dd>{{ statistics|get_item:rating }}</dd>